command:
  - python
  - databricks_app.py

env:
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/1066550024e48b7a"
  - name: DATABRICKS_CLIENT_ID
    value: "abd67f7d-c78b-4140-8658-56b10e8b4639"
  - name: DATABRICKS_CLIENT_SECRET
    value: "dose1e358fbbe8204fa11daa38169f1579d0"
  - name: GRADIO_ROOT_PATH
    value: ""
